### ISSUE TITLE
Demo App Issue -  Uncaught Error...bare specifier "@react-mf/root-config"

### ISSUE THREAD

**Issue by HJordan35** [react-microfrontends/root-config#10]
I was just playing around with the demo app the other day, but it appears there may have been something that changed recently. 

When attempting to access https://react.microfrontends.app/ - I receive the following error

![image](https://user-images.githubusercontent.com/10759121/80036014-98299e00-84b6-11ea-96c1-0997940ae866.png)

I cleared my cache, attempted accessing in an incognito window, and made sure devTools were disabled.

**Comment by internettrans** [comment]
Hi @HJordan35 - this is related to an errant npm publish I made to systemjs. To fix, you can pin systemjs to a specific version. @TheMcMurder showed how to do so in #9. However, it's easier for the single-spa core team to maintain all our example repos if we don't pin to a specific version (so that we don't have to constantly PR all the examples). The systemjs issue has been fixed, but we're waiting on the jsdelivr cache to bust for everything to be better again. See related https://github.com/single-spa/single-spa/issues/522 and https://github.com/single-spa/single-spa/issues/523
