### ISSUE TITLE
single-spa polyfill for ie11

### ISSUE THREAD

**Issue by dseaman1-chwy** [react-microfrontends/root-config#19]
Sadly, IE11 is still in use by some users. Using single-spa has been great, except that we cannot get it to function on IE11. There are a few mentions to polyfills in the documentation, but the only one of any substance is in the angular-specific section, and the demo commit linked from there utilizes an index.html to add polyfills. 

We have a structure more similar to this repo - a root-config.js and an index.ejs. Is there a chance that you could make this repo compatible with running on IE11 so that other could us this as an all-browser example?

**Comment by internettrans** [comment]
Hi @dseaman1-chwy - all of the systemjs and single-spa libraries support IE11. I have personally confirmed that they work in IE11 several times, and fix any IE11-related bugs that surface. The main polyfills you need are `Promise` and `fetch`, as explained in the SystemJS documentation at https://github.com/systemjs/systemjs#ie11-support. Additionally, you should make sure to set your [browserslist](https://github.com/browserslist/browserslist) to support IE11. If things still don't work after that, try adding [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) to your root-config's index.ejs file and that will also help.

I'd prefer not making this example compatible with IE11, since IE11 is nearing EOL and the example here is exclusively used by developers who very rarely ever browse with IE11.

**Comment by dseaman1-chwy** [comment]
Thanks for all the resources!

As for that last bit - I totally hear you, and as a developer I want nothing more than to never interact with IE again. But, sadly, while _developers_ rarely ever browse with it, many users still do. At the size and scale we are trying to implement single-spa, we don't have much choice but to give it a snorkel as it continues to sink. That's the only reason why I asked to make the examples compatible - I imagine I'm not the only one stuck with this issue. But I do understand it might not be worth the work on your end.

**Comment by internettrans** [comment]
I am not going to make this example IE11 compatible - there are hundreds of organizations using single-spa and it's not practical to modify the examples to cater towards each one's requirements. I've provided detailed instructions for you to follow. Also, I have confirmed quite recently that IE11 + single-spa works as part of doing some single-spa consulting with a company.

**Comment by dseaman1-chwy** [comment]
Sorry for the delayed response - short version, your instructions didn't work and while IE11 is nearing end of life, users still use it which means market share money is on the table whether we as developers like it or not. I think having _examples of how to use your library_ adapted to work with _browsers that are still in use_ is really not asking for an unreasonable "modified example for one's requirements". But, I see you've closed the issue, so we'll have to chase down another solution.

**Comment by internettrans** [comment]
If you'd like to report a bug, please open an issue with a stacktrace and way to demonstrate the problem. I have followed the instructions above several times in the last month and confirmed that things work in IE11.
