### ISSUE TITLE
Chrome SSL error

### ISSUE THREAD

**Issue by garethbjohnson** [react-microfrontends/root-config#22]
When I follow the local development instructions, I get this error when I try to go to `https://localhost:9000/react-mf-root-config.js` in Chrome:

> ### This site can’t provide a secure connection
> **localhost** sent an invalid response.
>
> ERR_SSL_PROTOCOL_ERROR

This happens even after following the linked Chrome instructions for SSL problems. When I go to `chrome://flags/#allow-insecure-localhost`, I see the flag enabled for "Allow invalid certificates for resources loaded from localhost." Restarting Chrome did not help.

I am using Chrome 87 on macOS 10.15.

**Comment by internettrans** [comment]
The root config runs on http instead of https by default - the idea was to avoid the complications of SSL certificates but it seems in this case it caused the opposite confusion. Webpack-dev-server doesn't support serving both on port http and https at the same time.

You can either run the root config over https with `yarn start --https`, or you can go to http://localhost:9000/react-mf-root-config.js instead of the https version.

I see that the docs are wrong - I'll update them.

**Comment by internettrans** [comment]
Here was the commit that updates the docs - https://github.com/react-microfrontends/root-config/blob/master/README.md
