### ISSUE TITLE
yarn start failed

### ISSUE THREAD

**Issue by dfang** [react-microfrontends/root-config#29]
```
λ  yarn start
yarn run v1.22.11
$ webpack serve --port 9000 --env isLocal
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'firewall'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mabashian** [comment]
Seeing this as well.  Looks like the same error was filed in #30.

**Comment by internettrans** [comment]
As instructed in the readme, this project uses pnpm rather than yarn. When you use pnpm, the project works because it uses the correct lockfile.

The reason that yarn doesn't work with the current package.json is because there was a new release of webpack-dev-server that broke things. See single-spa/create-single-spa#309 where this was discussed, and it was released in a new major version of webpack-config-single-spa.

I upgraded to the latest dependency versions in #31 and it likely makes things work when using yarn. But it's still best to use pnpm to ensure proper dependency resolution.
