### ISSUE TITLE
webpack-cli problem

### ISSUE THREAD

**Issue by baorr** [react-microfrontends/root-config#30]
1. git clone https://github.com/react-microfrontends/root-config.git
2. yarn install
2. yarn start
then error comes, can you recommend a working partner for me(webpack, wecpack-cli, webpack-dev-server)
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'firewall'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
 - options.client has an unknown property 'host'. These properties are valid:
   object { logging?, overlay?, progress?, webSocketTransport?, webSocketURL? }

**Comment by internettrans** [comment]
As instructed in the readme, this project uses `pnpm` rather than `yarn`. When you use pnpm, the project works because it uses the correct lockfile.

The reason that yarn doesn't work with the current package.json is because there was a new release of webpack-dev-server that broke things. See https://github.com/single-spa/create-single-spa/issues/309 where this was discussed, and it was released in a new major version of webpack-config-single-spa. I'll upgrade this project to those latest versions so that yarn will likely work, too, but you should use the correct package manager to ensure correct dependency resolution.
